// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1tZAEZH4DjuNgylyHPB1fqcA58aMFrEo',
    appId: '1:413771361798:ios:46c54ecbc4812762555d87',
    messagingSenderId: '413771361798',
    projectId: 'pintra-pelindo',
    storageBucket: 'pintra-pelindo.firebasestorage.app',
    iosBundleId: 'com.example.pintra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1tZAEZH4DjuNgylyHPB1fqcA58aMFrEo',
    appId: '1:413771361798:ios:46c54ecbc4812762555d87',
    messagingSenderId: '413771361798',
    projectId: 'pintra-pelindo',
    storageBucket: 'pintra-pelindo.firebasestorage.app',
    iosBundleId: 'com.example.pintra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKsn2ebNymOKC1gL_XYatihqCMiOItVN8',
    appId: '1:413771361798:web:c4853ee962d77d10555d87',
    messagingSenderId: '413771361798',
    projectId: 'pintra-pelindo',
    authDomain: 'pintra-pelindo.firebaseapp.com',
    storageBucket: 'pintra-pelindo.firebasestorage.app',
    measurementId: 'G-5V8F6C4SS5',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKsn2ebNymOKC1gL_XYatihqCMiOItVN8',
    appId: '1:413771361798:web:c4853ee962d77d10555d87',
    messagingSenderId: '413771361798',
    projectId: 'pintra-pelindo',
    authDomain: 'pintra-pelindo.firebaseapp.com',
    storageBucket: 'pintra-pelindo.firebasestorage.app',
    measurementId: 'G-5V8F6C4SS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaxflQwkre9EtEiw8XyM9Y908x12J88v0',
    appId: '1:413771361798:android:5395f625229cdeda555d87',
    messagingSenderId: '413771361798',
    projectId: 'pintra-pelindo',
    storageBucket: 'pintra-pelindo.firebasestorage.app',
  );

}